[versions]
kotlin = "1.8.22"
kotlinx-coroutines = "1.7.2"

gradle-versions = "0.47.0"
detekt = "1.23.0"

okio = "3.3.0"

[libraries]
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

