name: Lint and Test

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [main]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Detekt base91
        run: ./gradlew :base91:detektMetadataMain
      - name: Detekt base91-streaming
        run: ./gradlew :base91-streaming:detektMetadataMain
      - name: Test base91
        run: ./gradlew :base91:jvmTest
      - name: Test base91-streaming
        run: ./gradlew :base91-streaming:jvmTest
      - name: Stop Gradle
        run: ./gradlew --stop
